/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelNilai.java
 *
 * Created on Nov 27, 2011, 8:36:19 PM
 */
package pretest.server.ui.panel;

import java.rmi.RemoteException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import pretest.entity.NilaiBs;
import pretest.entity.NilaiMc;
import pretest.server.PretestServer;
import pretest.server.impl.BsPretestServiceImpl;
import pretest.server.impl.McPretestServiceImpl;
import pretest.service.BsPretestService;

/**
 *
 * @author bahrie
 */
public class PanelNilai extends javax.swing.JPanel {

    /** Creates new form PanelNilai */
    public PanelNilai() throws RemoteException {
        initComponents();
        bsPretestServiceImpl=new BsPretestServiceImpl();
        mcPretestServiceImpl=new McPretestServiceImpl();
        bsPretestServiceImpl.setEm(PretestServer.getEntityManager());
        mcPretestServiceImpl.setEm(PretestServer.getEntityManager());
        listNilaiBs=bsPretestServiceImpl.findNilaiBss();
        listNilaiMc=mcPretestServiceImpl.findNilaiMcs();
        isiTableBs();
        isiTableMc();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBS = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelMC = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nilai Benar Salah"));

        tabelBS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelBS);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nilai Pilihan Ganda"));

        tabelMC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelMC);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(75, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelBS;
    private javax.swing.JTable tabelMC;
    // End of variables declaration//GEN-END:variables
    private List<NilaiBs> listNilaiBs;
    private List<NilaiMc> listNilaiMc;
    private BsPretestServiceImpl bsPretestServiceImpl;
    private McPretestServiceImpl mcPretestServiceImpl;
    
    private void isiTableBs() {
        Object data[][] = new Object[listNilaiBs.size()][5];
        int row = 0;
        for (NilaiBs nb : listNilaiBs) {
            data[row][0] = nb.getMahasiswa().getNim();
            data[row][1] = nb.getMahasiswa().getNama();
            data[row][2] = nb.getPertemuanPraktikum().getPraktikum().getNama();
            data[row][3] = nb.getPertemuanPraktikum().getPertemuanKe();
            data[row][4] = nb.getNilai();
            row++;
        }
        String titile[] = {"Nim", "Nama", "Praktikum", "Ke","Nilai"};
        tabelBS.setModel(new DefaultTableModel(data, titile));
        jScrollPane1.setViewportView(tabelBS);
    }
    
    private void isiTableMc() {
        Object data[][] = new Object[listNilaiMc.size()][5];
        int row = 0;
        for (NilaiMc nm : listNilaiMc) {
            data[row][0] = nm.getMahasiswa().getNim();
            data[row][1] = nm.getMahasiswa().getNama();
            data[row][2] = nm.getPertemuanPraktikum().getPraktikum().getNama();
            data[row][3] = nm.getPertemuanPraktikum().getPertemuanKe();
            data[row][4] = nm.getNilai();
            row++;
        }
        String titile[] = {"Nim", "Nama", "Praktikum", "Ke","Nilai"};
        tabelMC.setModel(new DefaultTableModel(data, titile));
        jScrollPane2.setViewportView(tabelMC);
    }
}
