/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelSetting.java
 *
 * Created on Jan 21, 2012, 9:41:20 PM
 */
package pretest.server.ui.panel;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pretest.entity.Setting;
import pretest.server.PretestServer;
import pretest.server.impl.MahasiswaServiceImpl;

/**
 *
 * @author bahrie
 */
public class PanelSetting extends javax.swing.JPanel {

    /** Creates new form PanelSetting */
    public PanelSetting() throws RemoteException {
        initComponents();
        mahasiswaServiceImpl = new MahasiswaServiceImpl();
        mahasiswaServiceImpl.setEm(PretestServer.getEntityManager());
        setting = mahasiswaServiceImpl.getSetting();

        textJam.setText(setting.getJam() + "");
        
        textLulus.setText(setting.getBataLulus().intValue()+"");
        textMenit.setText(setting.getMenit() + "");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textJam = new javax.swing.JTextField();
        textMenit = new javax.swing.JTextField();
        textLulus = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonUpate = new javax.swing.JButton();

        jLabel1.setText(" Waktu Pengerjaan :");

        jLabel2.setText("Batas Lulus :");

        textJam.setEditable(false);

        textMenit.setEditable(false);

        textLulus.setEditable(false);

        jLabel3.setText("Jam");

        jLabel4.setText("Menit");

        buttonUpate.setText("Update");
        buttonUpate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonUpate)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textLulus)
                            .addComponent(textJam, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textMenit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMenit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textLulus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonUpate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void buttonUpateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpateActionPerformed
    try {
        buttonUpateActionPerformed();
    } catch (RemoteException ex) {
        Logger.getLogger(PanelSetting.class.getName()).log(Level.SEVERE, null, ex);
    }
}//GEN-LAST:event_buttonUpateActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonUpate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textJam;
    private javax.swing.JTextField textLulus;
    private javax.swing.JTextField textMenit;
    // End of variables declaration//GEN-END:variables
    private Setting setting;
    private MahasiswaServiceImpl mahasiswaServiceImpl;

    private void setEnableButton(boolean enable) {
        textJam.setEditable(enable);
        textLulus.setEditable(enable);
        textMenit.setEditable(enable);
    }
    
    private boolean cekText(){
        if(textJam.getText().matches("\\p{Digit}+") && textLulus.getText().matches("\\p{Digit}+") 
                && textMenit.getText().matches("\\p{Digit}+") && Integer.parseInt(textMenit.getText())<=60 
                && Integer.parseInt(textLulus.getText())>0 && Integer.parseInt(textLulus.getText())<100){
            return true;
        }
        return false;
    }

    private void buttonUpateActionPerformed() throws RemoteException {
        if (buttonUpate.getText().equals("Update")) {
            setEnableButton(true);

            buttonUpate.setText("save");
        } else {
            if (setting == null) {
                setting = new Setting();
            }
            if(cekText()){
            setting.setBataLulus(Double.parseDouble(textLulus.getText()));
            setting.setJam(Integer.parseInt(textJam.getText()));
            setting.setMenit(Integer.parseInt(textMenit.getText()));

            mahasiswaServiceImpl.updateSetting(setting);
            setEnableButton(false);
            buttonUpate.setText("Update");
            }else{
                JOptionPane.showMessageDialog(this, "format tidak sesuai dengan biasanya. tidak boleh input selain angka");
            }
        }
    }
}
