/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPraktikum.java
 *
 * Created on Dec 5, 2011, 7:43:16 PM
 */
package pretest.server.ui.panel;

import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import pretest.entity.PertemuanPraktikum;
import pretest.entity.Praktikum;

import pretest.server.PretestServer;
import pretest.server.impl.PraktikumServiceImpl;
import pretest.server.util.BeanComboBoxModel;

/**
 *
 * @author bahrie
 */
public class PanelPertemuanPraktikum extends javax.swing.JPanel {

    /** Creates new form PanelPraktikum */
    public PanelPertemuanPraktikum() throws RemoteException {
        initComponents();
        praktikumService = new PraktikumServiceImpl();
        praktikumService.setEm(PretestServer.getEntityManager());
        //statusAwal();
        tablePertemuanPraktikum.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                initSelectTable();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePertemuanPraktikum = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textKe = new javax.swing.JTextField();
        buttonReload = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboPraktikum = new javax.swing.JComboBox();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Pertemuan"));

        tablePertemuanPraktikum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablePertemuanPraktikum);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Pertemuan Praktikum"));

        jLabel1.setText("Ke");

        buttonReload.setText("Reload");
        buttonReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReloadActionPerformed(evt);
            }
        });

        buttonSimpan.setText("Tambah");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonUbah.setText("Ubah");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        jLabel2.setText("Praktikum");

        comboPraktikum.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPraktikumItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonReload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonHapus))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboPraktikum, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textKe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboPraktikum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonReload)
                    .addComponent(buttonSimpan)
                    .addComponent(buttonUbah)
                    .addComponent(buttonHapus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void buttonReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReloadActionPerformed
    statusAwal();
}//GEN-LAST:event_buttonReloadActionPerformed

private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
    buttonSimpanActionPerformed();
}//GEN-LAST:event_buttonSimpanActionPerformed

private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
    buttonUbahActionPerformed();
}//GEN-LAST:event_buttonUbahActionPerformed

private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
    buttonHapusActionPerformed();
}//GEN-LAST:event_buttonHapusActionPerformed

private void comboPraktikumItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPraktikumItemStateChanged
    comboPraktikumItemStateChanged();
}//GEN-LAST:event_comboPraktikumItemStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonReload;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JComboBox comboPraktikum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePertemuanPraktikum;
    private javax.swing.JTextField textKe;
    // End of variables declaration//GEN-END:variables
    private Praktikum praktikum;
    private PertemuanPraktikum pertemuanPraktikum;
    private List<Praktikum> praktikums;
    private List<PertemuanPraktikum> pertemuanPraktikums;
    private PraktikumServiceImpl praktikumService;

    private void statusAwal() {
        reModelComboPraktikum();
        clearText();
        loadAllData();
        isiTable();
        buttonHapus.setEnabled(false);
        buttonUbah.setEnabled(false);
        buttonSimpan.setEnabled(true);
    }

    private void isiTable() {
        Object data[][] = new Object[pertemuanPraktikums.size()][2];
        int row = 0;
        for (PertemuanPraktikum pp : pertemuanPraktikums) {
            data[row][0] = pp.getPraktikum().getNama();
            data[row][1] = pp.getPertemuanKe();

            row++;
        }
        String titile[] = {"Praktikum", "Pertemuan Ke"};
        tablePertemuanPraktikum.setModel(new DefaultTableModel(data, titile));
        jScrollPane1.setViewportView(tablePertemuanPraktikum);
    }

    private void loadAllData() {
       
            pertemuanPraktikums = new ArrayList<PertemuanPraktikum>();
            pertemuanPraktikums = praktikumService.findPertemuanPraktikums();
        
    }

//    private void loadComboPraktikum() {
//       
//            comboPraktikum.removeAllItems();
//            praktikums = praktikumService.findPraktikums();
//            for (Praktikum p : praktikums) {
//                comboPraktikum.addItem(p.getNama());
//            }
//        
//    }

    private void clearText() {
        textKe.setText("");
        comboPraktikum.setSelectedIndex(-1);
    }

    private void isiText() {
        textKe.setText(pertemuanPraktikum.getPertemuanKe() + "");
        comboPraktikum.setSelectedIndex(praktikums.indexOf(pertemuanPraktikum.getPraktikum()));
    }

    private void initSelectTable() {
        if (tablePertemuanPraktikum.getSelectedRow() >= 0) {
            pertemuanPraktikum = pertemuanPraktikums.get(tablePertemuanPraktikum.getSelectedRow());
            isiText();
            buttonHapus.setEnabled(true);
            buttonUbah.setEnabled(true);
            buttonSimpan.setEnabled(false);
        }
    }

    private boolean cekText() {
        if (!textKe.getText().isEmpty() && comboPraktikum.getSelectedIndex() >= 0) {
            return true;
        }
        return false;
    }

    private void comboPraktikumItemStateChanged() {
        if (comboPraktikum.getSelectedIndex() >= 0) {
            praktikum = praktikums.get(comboPraktikum.getSelectedIndex());
        }
    }

    private void buttonSimpanActionPerformed() {
        if (cekText()) {
            
                pertemuanPraktikum = new PertemuanPraktikum();
                pertemuanPraktikum.setPertemuanKe(Integer.parseInt(textKe.getText().trim()));
                pertemuanPraktikum.setPraktikum(praktikum);
                praktikumService.save(pertemuanPraktikum);
                statusAwal();
            
        } else {
            JOptionPane.showMessageDialog(null, "text field tidak boleh kosong");
        }
    }

    private void buttonUbahActionPerformed() {
        if (cekText()) {
            
                pertemuanPraktikum.setPertemuanKe(Integer.parseInt(textKe.getText().trim()));
                pertemuanPraktikum.setPraktikum(praktikum);
                praktikumService.save(praktikum);
                statusAwal();
            
        } else {
            JOptionPane.showMessageDialog(null, "text field tidak boleh kosong");
        }
    }

    private void buttonHapusActionPerformed() {
        if (tablePertemuanPraktikum.getSelectedRow() >= 0) {
           
                pertemuanPraktikum = pertemuanPraktikums.get(tablePertemuanPraktikum.getSelectedRow());
                praktikumService.delete(pertemuanPraktikum);
                JOptionPane.showMessageDialog(null, "data sudah dihapus");
            
        }
        statusAwal();
    }

    public void reModelComboPraktikum() {
        if (!comboPraktikum.isVisible()) {
            return;
        }

        boolean[] fieldVisible = {false, true};
        praktikums=praktikumService.findPraktikums();
        BeanComboBoxModel model = new BeanComboBoxModel(praktikums, fieldVisible, " - ");
        comboPraktikum.setModel(model);
//        country = null;
    }
  
}
