/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelInputPraktikum.java
 *
 * Created on Dec 31, 2011, 6:36:57 PM
 */
package pretest.server.ui.panel;

/**
 *
 * @author bahrie
 */
public class PanelInputPraktikum extends javax.swing.JPanel {

    /** Creates new form PanelInputPraktikum */
    public PanelInputPraktikum() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            panelPraktikum1 = new pretest.server.ui.panel.PanelPraktikum();
        } catch (java.rmi.RemoteException e1) {
            e1.printStackTrace();
        }
        try {
            panelPertemuanPraktikum1 = new pretest.server.ui.panel.PanelPertemuanPraktikum();
        } catch (java.rmi.RemoteException e1) {
            e1.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPraktikum1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPertemuanPraktikum1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPraktikum1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
            .addComponent(panelPertemuanPraktikum1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pretest.server.ui.panel.PanelPertemuanPraktikum panelPertemuanPraktikum1;
    private pretest.server.ui.panel.PanelPraktikum panelPraktikum1;
    // End of variables declaration//GEN-END:variables
}
