/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelSoalMc.java
 *
 * Created on Dec 4, 2011, 7:01:09 PM
 */
package pretest.server.ui.panel;

import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import pretest.entity.PertemuanPraktikum;
import pretest.entity.Praktikum;
import pretest.entity.SoalMc;
import pretest.entity.enuum.KunciMc;
import pretest.server.PretestServer;
import pretest.server.impl.McPretestServiceImpl;
import pretest.server.impl.PraktikumServiceImpl;

/**
 *
 * @author bahrie
 */
public class PanelSoalMc extends javax.swing.JPanel {

    /** Creates new form PanelSoalMc */
    public PanelSoalMc() throws RemoteException {
        initComponents();
        praktikumService = new PraktikumServiceImpl();
        mcPretestService = new McPretestServiceImpl();
        praktikumService.setEm(PretestServer.getEntityManager());
        mcPretestService.setEm(PretestServer.getEntityManager());
        statusAwal();

        tableSoalMc.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                initSelectedTable();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSoalMc = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        buttonAdd = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        comboPertemuan = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        textSoal = new javax.swing.JTextArea();
        comboPraktikum = new javax.swing.JComboBox();
        textCJawaban = new javax.swing.JTextField();
        textDJawaban = new javax.swing.JTextField();
        textBJawaban = new javax.swing.JTextField();
        textAJawaban = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboKunci = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buttonReload = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Soal Mc"));

        tableSoalMc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableSoalMc);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Soal Pilihan Ganda"));

        buttonAdd.setText("Tambah");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonUpdate.setText("Ubah");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        comboPertemuan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPertemuanItemStateChanged(evt);
            }
        });

        textSoal.setColumns(20);
        textSoal.setRows(5);
        jScrollPane2.setViewportView(textSoal);

        comboPraktikum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        comboPraktikum.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPraktikumItemStateChanged(evt);
            }
        });

        jLabel7.setText("C");

        jLabel8.setText("D");

        jLabel6.setText("B");

        jLabel5.setText("A");

        jLabel4.setText("Kunci");

        jLabel3.setText("Soal");

        jLabel2.setText("Pertemuan");

        jLabel1.setText("Praktikum");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textAJawaban, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textBJawaban, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textDJawaban, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textCJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(9, 9, 9))
                    .addComponent(comboPraktikum, 0, 521, Short.MAX_VALUE)
                    .addComponent(comboPertemuan, 0, 521, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(comboKunci, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboPraktikum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboPertemuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(textAJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(textBJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboKunci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        buttonReload.setText("Reload");
        buttonReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonReload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(buttonReload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDelete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboPraktikumItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPraktikumItemStateChanged
        if (comboPraktikum.getSelectedIndex() >= 0) {
            comboPraktikumItemStateChanged();
        }
}//GEN-LAST:event_comboPraktikumItemStateChanged

    private void comboPertemuanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPertemuanItemStateChanged
        if (comboPertemuan.getSelectedIndex() >= 0) {
            comboPertemuanItemStateChanged();
        }
}//GEN-LAST:event_comboPertemuanItemStateChanged

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        buttonAddActionPerformed();
}//GEN-LAST:event_buttonAddActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        buttonUpdateActionPerformed();
}//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        buttonDeleteActionPerformed();
}//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReloadActionPerformed
        statusAwal();
    }//GEN-LAST:event_buttonReloadActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonReload;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JComboBox comboKunci;
    private javax.swing.JComboBox comboPertemuan;
    private javax.swing.JComboBox comboPraktikum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableSoalMc;
    private javax.swing.JTextField textAJawaban;
    private javax.swing.JTextField textBJawaban;
    private javax.swing.JTextField textCJawaban;
    private javax.swing.JTextField textDJawaban;
    private javax.swing.JTextArea textSoal;
    // End of variables declaration//GEN-END:variables
    private Praktikum praktikum;
    private PertemuanPraktikum pertemuanPraktikum;
    private SoalMc soalMc;
    private List<SoalMc> soalMcList;
    private List<PertemuanPraktikum> pertemuanPraktikums;
    private List<Praktikum> praktikums;
    private PraktikumServiceImpl praktikumService;
    private McPretestServiceImpl mcPretestService;

    private void statusAwal() {
        loadComboPraktikum();
        initCombo();
        clearComponent();
        loadData();
        isiTable();
        buttonAdd.setEnabled(true);
        buttonDelete.setEnabled(false);
        buttonUpdate.setEnabled(false);
    }

    private void clearComponent() {
        comboKunci.setSelectedIndex(-1);
        comboPertemuan.removeAllItems();
        comboPraktikum.setSelectedIndex(-1);
        textSoal.setText("");
        textAJawaban.setText("");
        textBJawaban.setText("");
        textCJawaban.setText("");
        textDJawaban.setText("");

    }

    private void isiText() {
        textSoal.setText(soalMc.getSoal());
        textAJawaban.setText(soalMc.getA());
        textBJawaban.setText(soalMc.getB());
        textCJawaban.setText(soalMc.getC());
        textDJawaban.setText(soalMc.getD());
        comboKunci.setSelectedItem(KunciMc.valueOf(soalMc.getKunciMc() + ""));

        comboPraktikum.setSelectedIndex(praktikums.indexOf(soalMc.getPertemuanPraktikum().getPraktikum()));
        comboPertemuan.setSelectedIndex(pertemuanPraktikums.indexOf(soalMc.getPertemuanPraktikum()));


    }

    private void loadData() {
        
            soalMcList = new ArrayList<SoalMc>();
            soalMcList = mcPretestService.findSoalMcs();
        
    }

    private void loadComboPraktikum() {
        
            comboPraktikum.removeAllItems();
            praktikums = praktikumService.findPraktikums();
            for (Praktikum p : praktikums) {
                comboPraktikum.addItem(p.getNama());
            }
        
    }

    private void isiTable() {
        Object data[][] = new Object[soalMcList.size()][8];
        int row = 0;
        for (SoalMc sbs : soalMcList) {
            data[row][0] = sbs.getPertemuanPraktikum().getPraktikum().getNama();
            data[row][1] = sbs.getPertemuanPraktikum().getPertemuanKe();
            data[row][2] = sbs.getSoal();
            data[row][3] = sbs.getA();
            data[row][4] = sbs.getB();
            data[row][5] = sbs.getC();
            data[row][6] = sbs.getD();
            data[row][7] = sbs.getKunciMc();
            row++;
        }
        String titile[] = {"Praktikum", "Pertemuan", "Soal", "A", "B", "C", "D", "Kunci"};
        tableSoalMc.setModel(new DefaultTableModel(data, titile));
        jScrollPane1.setViewportView(tableSoalMc);
    }

    private void initCombo() {
        DefaultComboBoxModel model = new DefaultComboBoxModel(KunciMc.values());
        comboKunci.setModel(model);

    }

    private void initSelectedTable() {
        if (tableSoalMc.getSelectedRow() >= 0) {
            soalMc = soalMcList.get(tableSoalMc.getSelectedRow());
            isiText();
            buttonAdd.setEnabled(false);
            buttonDelete.setEnabled(true);
            buttonUpdate.setEnabled(true);
        }
    }

    private boolean cekText() {
        if (comboPraktikum.getSelectedIndex() >= 0
                && comboPertemuan.getSelectedIndex() >= 0
                && !textSoal.getText().isEmpty()
                && comboKunci.getSelectedIndex() >= 0
                && !textAJawaban.getText().isEmpty()
                && !textBJawaban.getText().isEmpty()
                && !textCJawaban.getText().isEmpty()
                && !textDJawaban.getText().isEmpty()) {
            return true;
        }
        return false;
    }

    private void comboPraktikumItemStateChanged() {
        
            praktikum = praktikums.get(comboPraktikum.getSelectedIndex());
            pertemuanPraktikums = praktikumService.findPraktikumPertemuans(praktikum);
            comboPertemuan.removeAllItems();
            for (PertemuanPraktikum pp : pertemuanPraktikums) {
                comboPertemuan.addItem(pp.getPertemuanKe());
            }
            comboPertemuan.setSelectedIndex(-1);
        
    }

    private void comboPertemuanItemStateChanged() {
        pertemuanPraktikum = pertemuanPraktikums.get(comboPertemuan.getSelectedIndex());
    }

    private void buttonAddActionPerformed() {
        if (cekText()) {
           
                soalMc = new SoalMc();
                soalMc.setSoal(textSoal.getText());
                soalMc.setA(textAJawaban.getText());
                soalMc.setB(textBJawaban.getText());
                soalMc.setC(textCJawaban.getText());
                soalMc.setD(textDJawaban.getText());
                soalMc.setKunciMc(KunciMc.valueOf(comboKunci.getSelectedItem() + ""));
                soalMc.setPertemuanPraktikum(pertemuanPraktikum);
                mcPretestService.save(soalMc);
                statusAwal();
            
        } else {
            JOptionPane.showMessageDialog(null, "tidak boleh ada yang kosong");
        }
    }

    private void buttonUpdateActionPerformed() {
        if (cekText()) {
           
                soalMc.setSoal(textSoal.getText());
                soalMc.setA(textAJawaban.getText());
                soalMc.setB(textBJawaban.getText());
                soalMc.setC(textCJawaban.getText());
                soalMc.setD(textDJawaban.getText());
                soalMc.setKunciMc(KunciMc.valueOf(comboKunci.getSelectedItem() + ""));
                soalMc.setPertemuanPraktikum(pertemuanPraktikum);
                mcPretestService.save(soalMc);
                statusAwal();
            
        } else {
            JOptionPane.showMessageDialog(null, "tidak boleh kosong");
        }
    }

    private void buttonDeleteActionPerformed() {
        if (tableSoalMc.getSelectedRow() >= 0) {
            
                soalMc = soalMcList.get(tableSoalMc.getSelectedRow());
                mcPretestService.delete(soalMc);
                JOptionPane.showMessageDialog(null, "data berhasil di hapus");
                statusAwal();
            
        }
    }
}
