/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelSoalBs.java
 *
 * Created on Dec 4, 2011, 6:45:34 PM
 */
package pretest.server.ui.panel;

import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import pretest.entity.PertemuanPraktikum;
import pretest.entity.Praktikum;
import pretest.entity.SoalBs;
import pretest.entity.enuum.KunciBs;
import pretest.server.PretestServer;
import pretest.server.impl.BsPretestServiceImpl;
import pretest.server.impl.PraktikumServiceImpl;

/**
 *
 * @author bahrie
 */
public class PanelSoalBs extends javax.swing.JPanel {

    /** Creates new form PanelSoalBs */
    public PanelSoalBs() throws RemoteException {
        initComponents();
        praktikumService = new PraktikumServiceImpl();
        bsPretestService = new BsPretestServiceImpl();
        praktikumService.setEm(PretestServer.getEntityManager());
        bsPretestService.setEm(PretestServer.getEntityManager());
        statusAwal();

        tableSoalBs.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                initSelectedTable();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSoalBs = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        buttonAdd = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        comboPraktikum = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboPertemuan = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        textSoal = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboKunci = new javax.swing.JComboBox();
        buttonReload = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Soal Benar Salah"));

        tableSoalBs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableSoalBs);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Soal Benar Salah"));

        buttonAdd.setText("Tambah");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonUpdate.setText("Ubah");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        comboPraktikum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        comboPraktikum.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPraktikumItemStateChanged(evt);
            }
        });

        jLabel1.setText("Praktikum");

        jLabel2.setText("Pertemuan");

        comboPertemuan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPertemuanItemStateChanged(evt);
            }
        });

        textSoal.setColumns(20);
        textSoal.setRows(5);
        jScrollPane2.setViewportView(textSoal);

        jLabel3.setText("Soal");

        jLabel4.setText("Kunci");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboKunci, 0, 302, Short.MAX_VALUE)
                    .addComponent(comboPertemuan, 0, 302, Short.MAX_VALUE)
                    .addComponent(comboPraktikum, 0, 302, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboPraktikum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboPertemuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboKunci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)))
        );

        buttonReload.setText("Reload");
        buttonReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(buttonAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(buttonDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(buttonReload, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(buttonReload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDelete))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboPraktikumItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPraktikumItemStateChanged
        if (comboPraktikum.getSelectedIndex() >= 0) {
            comboPraktikumItemStateChanged();
        }
}//GEN-LAST:event_comboPraktikumItemStateChanged

    private void comboPertemuanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPertemuanItemStateChanged
        if (comboPertemuan.getSelectedIndex() >= 0) {
            comboPertemuanItemStateChanged();
        }
}//GEN-LAST:event_comboPertemuanItemStateChanged

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        buttonAddActionPerformed();
}//GEN-LAST:event_buttonAddActionPerformed

    private void buttonReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReloadActionPerformed
        statusAwal();
    }//GEN-LAST:event_buttonReloadActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        buttonUpdateActionPerformed();
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        buttonDeleteActionPerformed();
    }//GEN-LAST:event_buttonDeleteActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonReload;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JComboBox comboKunci;
    private javax.swing.JComboBox comboPertemuan;
    private javax.swing.JComboBox comboPraktikum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableSoalBs;
    private javax.swing.JTextArea textSoal;
    // End of variables declaration//GEN-END:variables
    private Praktikum praktikum;
    private PertemuanPraktikum pertemuanPraktikum;
    private SoalBs soalBs;
    private List<SoalBs> soalBsList;
    private List<PertemuanPraktikum> pertemuanPraktikums;
    private List<Praktikum> praktikums;
    private PraktikumServiceImpl praktikumService;
    private BsPretestServiceImpl bsPretestService;

    private void statusAwal() {
        loadComboPraktikum();
        initCombo();
        clearComponent();
        loadData();
        isiTable();
        buttonAdd.setEnabled(true);
        buttonDelete.setEnabled(false);
        buttonUpdate.setEnabled(false);

    }

    private void clearComponent() {
        comboKunci.setSelectedIndex(-1);
        comboPertemuan.removeAllItems();
        comboPraktikum.setSelectedIndex(-1);
        textSoal.setText("");
    }

    private void loadData() {
        
            soalBsList = new ArrayList<SoalBs>();
            soalBsList = bsPretestService.findSoalBss();
        
    }

    private void loadComboPraktikum() {
        
            comboPraktikum.removeAllItems();
            praktikums = praktikumService.findPraktikums();
            for (Praktikum p : praktikums) {
                comboPraktikum.addItem(p.getNama());
            }
        
    }

    private void isiTable() {
        Object data[][] = new Object[soalBsList.size()][4];
        int row = 0;
        for (SoalBs sbs : soalBsList) {
            data[row][0] = sbs.getPertemuanPraktikum().getPraktikum().getNama();
            data[row][1] = sbs.getPertemuanPraktikum().getPertemuanKe();
            data[row][2] = sbs.getSoal();
            data[row][3] = sbs.getKunci();
            row++;
        }
        String titile[] = {"Praktikum", "Pertemuan", "Soal", "Kunci"};
        tableSoalBs.setModel(new DefaultTableModel(data, titile));
        jScrollPane1.setViewportView(tableSoalBs);
    }

    private void initCombo() {
        DefaultComboBoxModel model = new DefaultComboBoxModel(KunciBs.values());
        comboKunci.setModel(model);

    }

    private void initSelectedTable() {
        if (tableSoalBs.getSelectedRow() >= 0) {
            soalBs = soalBsList.get(tableSoalBs.getSelectedRow());
            isiText();
            buttonAdd.setEnabled(false);
            buttonDelete.setEnabled(true);
            buttonUpdate.setEnabled(true);
        }
    }

    private void isiText() {
        textSoal.setText(soalBs.getSoal());
        comboKunci.setSelectedItem(KunciBs.valueOf(soalBs.getKunci() + ""));
        comboPraktikum.setSelectedIndex(praktikums.indexOf(soalBs.getPertemuanPraktikum().getPraktikum()));
        comboPertemuan.setSelectedIndex(pertemuanPraktikums.indexOf(soalBs.getPertemuanPraktikum()));
    }

    private boolean cekText() {
        if (comboPraktikum.getSelectedIndex() >= 0
                && comboPertemuan.getSelectedIndex() >= 0
                && !textSoal.getText().isEmpty()
                && comboKunci.getSelectedIndex() >= 0) {
            return true;
        }
        return false;
    }

    private void buttonAddActionPerformed() {
        if(cekText()){
           
                soalBs = new SoalBs();
                soalBs.setPertemuanPraktikum(pertemuanPraktikum);
                soalBs.setSoal(textSoal.getText().trim());
                soalBs.setKunci(KunciBs.valueOf(comboKunci.getSelectedItem() + ""));
                bsPretestService.save(soalBs);
                statusAwal();
           
        }else{
            JOptionPane.showMessageDialog(null, "harus di isi semua");
        }
    }

    private void buttonUpdateActionPerformed() {
        if(cekText()){
           
                soalBs.setPertemuanPraktikum(pertemuanPraktikum);
                soalBs.setSoal(textSoal.getText().trim());
                soalBs.setKunci(KunciBs.valueOf(comboKunci.getSelectedItem() + ""));
                bsPretestService.save(soalBs);
                statusAwal();
            
        }else{
            JOptionPane.showMessageDialog(null, "harus di isi semua");
        }
    }

    private void buttonDeleteActionPerformed() {
        if (tableSoalBs.getSelectedRow() >= 0) {
         
                soalBs = soalBsList.get(tableSoalBs.getSelectedRow());
                bsPretestService.delete(soalBs);
                JOptionPane.showMessageDialog(null, "data berhasil di hapus");
                statusAwal();
            
        }
    }

    private void comboPraktikumItemStateChanged() {
       
            praktikum = praktikums.get(comboPraktikum.getSelectedIndex());
            pertemuanPraktikums = praktikumService.findPraktikumPertemuans(praktikum);
            comboPertemuan.removeAllItems();
            for (PertemuanPraktikum pp : pertemuanPraktikums) {
                comboPertemuan.addItem(pp.getPertemuanKe());
            }
            comboPertemuan.setSelectedIndex(-1);
        
    }

    private void comboPertemuanItemStateChanged() {
        pertemuanPraktikum = pertemuanPraktikums.get(comboPertemuan.getSelectedIndex());
    }
}
