/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelKoneksi.java
 *
 * Created on Dec 2, 2011, 9:40:44 PM
 */
package pretest.client.panel;

import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pretest.client.util.KonekListener;
import pretest.service.BsPretestService;

/**
 *
 * @author bahrie
 */
public class PanelKoneksi extends javax.swing.JPanel {
private static BsPretestService bsPretestService;
    /** Creates new form PanelKoneksi */
    public PanelKoneksi() {
        initComponents();
    }
    
    private boolean testKoneksi() {
        try {
            bsPretestService=(BsPretestService) Naming.lookup("rmi://"+textIp.getText()+":4562/bsPretestService");
            if(bsPretestService !=null){
                return true;
            }
            
        } catch (NotBoundException ex) {
            Logger.getLogger(PanelKoneksi.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        } catch (MalformedURLException ex) {
            Logger.getLogger(PanelKoneksi.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        } catch (RemoteException ex) {
            Logger.getLogger(PanelKoneksi.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
        return false;
    }

    private void buttonOkKoneksiActionPerformed(){
       
            if(testKoneksi()){
                JOptionPane.showMessageDialog(null, "koneksi ok");
                listener.konek(textIp.getText());
            }else{
                JOptionPane.showMessageDialog(null, "koneksi gagal");
            }
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textIp = new javax.swing.JTextField();
        buttonOkKoneksi = new javax.swing.JButton();

        jLabel1.setText("Masukkan Alamat IP Server :");

        textIp.setText("localhost");

        buttonOkKoneksi.setText("Ok");
        buttonOkKoneksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkKoneksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonOkKoneksi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textIp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOkKoneksi)
                .addContainerGap(200, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOkKoneksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkKoneksiActionPerformed
        buttonOkKoneksiActionPerformed();
        
    }//GEN-LAST:event_buttonOkKoneksiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOkKoneksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textIp;
    // End of variables declaration//GEN-END:variables
    private KonekListener listener;

    public KonekListener getListener() {
        return listener;
    }

    public void setListener(KonekListener listener) {
        this.listener = listener;
    }
    
    
}
