/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MFrame.java
 *
 * by Saiful Bahri
 * http://bahrie27.wordpress.com/
 * twitter : @bahrie127
 *
 * Created on Dec 4, 2011, 6:14:37 PM
 */
package pretest.server.ui.frame;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

import pretest.server.ui.panel.PanelInputPraktikum;
import pretest.server.ui.panel.PanelLogin;
import pretest.server.ui.panel.PanelMahasiswa;
import pretest.server.ui.panel.PanelNilai;
import pretest.server.ui.panel.PanelSoalBs;
import pretest.server.ui.panel.PanelSoalMc;
import pretest.server.ui.panel.PanelStatistik;
import pretest.server.ui.panel.PanelWelcome;
import pretest.server.util.LoginListener;

public class MFrame extends javax.swing.JFrame {

    /** Creates new form MFrame */
    public MFrame() {
        initComponents();
        panelLogin = new PanelLogin();
        initPanelLogin();
        clearAndFillFrame(panelLogin);
        setVisibleButton(false);
        //setExtendedState(MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        buttonLogin = new javax.swing.JButton();
        buttonMahasiswa = new javax.swing.JButton();
        buttonSoalBs = new javax.swing.JButton();
        buttonSoalMc = new javax.swing.JButton();
        buttonStatistik = new javax.swing.JButton();
        buttonNilai = new javax.swing.JButton();
        buttonPraktikum = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pretest Server");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        buttonLogin.setText("Login");
        buttonLogin.setFocusable(false);
        buttonLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonLogin);

        buttonMahasiswa.setText("Mahasiswa");
        buttonMahasiswa.setFocusable(false);
        buttonMahasiswa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonMahasiswa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMahasiswaActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonMahasiswa);

        buttonSoalBs.setText("Soal Benar Salah");
        buttonSoalBs.setFocusable(false);
        buttonSoalBs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonSoalBs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonSoalBs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSoalBsActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonSoalBs);

        buttonSoalMc.setText("Soal Multiple choise");
        buttonSoalMc.setFocusable(false);
        buttonSoalMc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonSoalMc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonSoalMc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSoalMcActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonSoalMc);

        buttonStatistik.setText("Statistik");
        buttonStatistik.setFocusable(false);
        buttonStatistik.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonStatistik.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonStatistik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStatistikActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonStatistik);

        buttonNilai.setText("Nilai");
        buttonNilai.setFocusable(false);
        buttonNilai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonNilai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNilaiActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonNilai);

        buttonPraktikum.setText("Praktikum");
        buttonPraktikum.setFocusable(false);
        buttonPraktikum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPraktikum.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonPraktikum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPraktikumActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonPraktikum);

        mainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        showPanelLogin();
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void buttonMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMahasiswaActionPerformed
        try {
            showPanelMahasiswa();
        } catch (RemoteException ex) {
            Logger.getLogger(MFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonMahasiswaActionPerformed

    private void buttonSoalBsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSoalBsActionPerformed
        try {
            showPanelSoalBs();
        } catch (RemoteException ex) {
            Logger.getLogger(MFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonSoalBsActionPerformed

    private void buttonSoalMcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSoalMcActionPerformed
        try {
            showPanelSoalMc();
        } catch (RemoteException ex) {
            Logger.getLogger(MFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonSoalMcActionPerformed

    private void buttonStatistikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStatistikActionPerformed
        showPanelSoalStatistik();
    }//GEN-LAST:event_buttonStatistikActionPerformed

    private void buttonNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNilaiActionPerformed
        showPanelNilai();
    }//GEN-LAST:event_buttonNilaiActionPerformed

private void buttonPraktikumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPraktikumActionPerformed
    showPanelPraktikum();
}//GEN-LAST:event_buttonPraktikumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonMahasiswa;
    private javax.swing.JButton buttonNilai;
    private javax.swing.JButton buttonPraktikum;
    private javax.swing.JButton buttonSoalBs;
    private javax.swing.JButton buttonSoalMc;
    private javax.swing.JButton buttonStatistik;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
    private PanelLogin panelLogin;
    private PanelMahasiswa panelMahasiswa;
    private PanelNilai panelNilai;
    private PanelSoalBs panelSoalBs;
    private PanelSoalMc panelSoalMc;
    private PanelStatistik panelStatistik;
    private PanelWelcome panelWelcome;
    private PanelInputPraktikum panelInputPraktikum;


    private void clearAndFillFrame(JPanel panel) {
        mainPanel.removeAll();
        mainPanel.updateUI();
        mainPanel.add(panel);
        panel.setVisible(true);
    }

    private void initPanelLogin() {
        LoginListener listener = new LoginListener() {

            @Override
            public void login() {
                panelWelcome = new PanelWelcome();
                clearAndFillFrame(panelWelcome);
                buttonLogin.setText("Logout");
                setVisibleButton(true);
            }
        };
        panelLogin.setListener(listener);
    }

    private void showPanelLogin() {
        setVisibleButton(false);
        clearAndFillFrame(panelLogin);
    }

    private void showPanelMahasiswa() throws RemoteException {
        panelMahasiswa = new PanelMahasiswa();
        clearAndFillFrame(panelMahasiswa);
    }

    private void showPanelSoalBs() throws RemoteException {
        panelSoalBs = new PanelSoalBs();
        clearAndFillFrame(panelSoalBs);
    }

    private void showPanelSoalMc() throws RemoteException {
        panelSoalMc = new PanelSoalMc();
        clearAndFillFrame(panelSoalMc);
    }

    private void showPanelSoalStatistik() {
        panelStatistik = new PanelStatistik();
        clearAndFillFrame(panelStatistik);
    }

    private void showPanelNilai() {
        panelNilai = new PanelNilai();
        clearAndFillFrame(panelNilai);
    }

    private void showPanelPraktikum() {
        panelInputPraktikum=new PanelInputPraktikum();
        clearAndFillFrame(panelInputPraktikum);
    }

    private void setVisibleButton(boolean enable) {
        buttonLogin.setVisible(enable);
        buttonMahasiswa.setVisible(enable);
        buttonNilai.setVisible(enable);
        buttonSoalBs.setVisible(enable);
        buttonSoalMc.setVisible(enable);
        buttonStatistik.setVisible(enable);
    }
}
